In [1]:
#importando a biblioteca pandas e lendo o arquivo de 2023,2024 e 2025
import pandas as pd



df_2023 = pd.read_csv(
    "../data/raw/acidentes2023_todas_causas.csv",
    sep=";",
    encoding="latin1"
)


df_2024 = pd.read_csv(
    "../data/raw/acidentes2024_todas_causas.csv",
    sep=";",
    encoding="latin1"
)

df_2025 = pd.read_csv(
    "../data/raw/acidentes2025_todas_causas.csv",
    sep=";",
    encoding="latin1"
)

In [2]:
#exibindo o formato dos dataframes e visualizando o tamanho das tabelas
df_2023.shape, df_2024.shape, df_2025.shape

((571052, 37), (603215, 37), (528380, 37))

In [3]:
#visualizando as colunas do dataframes 2023
df_2023.columns

Index(['id', 'pesid', 'data_inversa', 'dia_semana', 'horario', 'uf', 'br',
       'km', 'municipio', 'causa_principal', 'causa_acidente',
       'ordem_tipo_acidente', 'tipo_acidente', 'classificacao_acidente',
       'fase_dia', 'sentido_via', 'condicao_metereologica', 'tipo_pista',
       'tracado_via', 'uso_solo', 'id_veiculo', 'tipo_veiculo', 'marca',
       'ano_fabricacao_veiculo', 'tipo_envolvido', 'estado_fisico', 'idade',
       'sexo', 'ilesos', 'feridos_leves', 'feridos_graves', 'mortos',
       'latitude', 'longitude', 'regional', 'delegacia', 'uop'],
      dtype='str')

In [4]:
df_2023.head(20)

,id,pesid,data_inversa,dia_semana,horario,uf,br,km,municipio,causa_principal,...,sexo,ilesos,feridos_leves,feridos_graves,mortos,latitude,longitude,regional,delegacia,uop
0,496506,1082142.0,2023-01-01,domingo,00:15:00,MG,116.0,587,MANHUACU,Não,...,Masculino,0.0,1.0,0.0,0.0,"-20,24173903","-42,15868042",SPRF-MG,DEL06-MG,UOP03-DEL06-MG
1,496506,1082142.0,2023-01-01,domingo,00:15:00,MG,116.0,587,MANHUACU,Sim,...,Masculino,0.0,1.0,0.0,0.0,"-20,24173903","-42,15868042",SPRF-MG,DEL06-MG,UOP03-DEL06-MG
2,496506,1082142.0,2023-01-01,domingo,00:15:00,MG,116.0,587,MANHUACU,Não,...,Masculino,0.0,1.0,0.0,0.0,"-20,24173903","-42,15868042",SPRF-MG,DEL06-MG,UOP03-DEL06-MG
3,496506,1082142.0,2023-01-01,domingo,00:15:00,MG,116.0,587,MANHUACU,Sim,...,Masculino,0.0,1.0,0.0,0.0,"-20,24173903","-42,15868042",SPRF-MG,DEL06-MG,UOP03-DEL06-MG
4,496507,1082138.0,2023-01-01,domingo,00:20:00,MG,381.0,"686,5",LAVRAS,Sim,...,Masculino,0.0,1.0,0.0,0.0,"-21,17928973","-45,12256622",SPRF-MG,DEL04-MG,UOP02-DEL04-MG
5,496512,1082879.0,2023-01-01,domingo,00:55:00,RS,386.0,"353,2",ESTRELA,Não,...,Feminino,0.0,0.0,1.0,0.0,"-29,50160055","-51,94784403",SPRF-RS,DEL04-RS,UOP02-DEL04-RS
6,496512,1082877.0,2023-01-01,domingo,00:55:00,RS,386.0,"353,2",ESTRELA,Não,...,Feminino,0.0,0.0,1.0,0.0,"-29,50160055","-51,94784403",SPRF-RS,DEL04-RS,UOP02-DEL04-RS
7,496512,1082884.0,2023-01-01,domingo,00:55:00,RS,386.0,"353,2",ESTRELA,Não,...,Masculino,0.0,0.0,1.0,0.0,"-29,50160055","-51,94784403",SPRF-RS,DEL04-RS,UOP02-DEL04-RS
8,496512,1082224.0,2023-01-01,domingo,00:55:00,RS,386.0,"353,2",ESTRELA,Não,...,Masculino,0.0,0.0,1.0,0.0,"-29,50160055","-51,94784403",SPRF-RS,DEL04-RS,UOP02-DEL04-RS
9,496512,1082880.0,2023-01-01,domingo,00:55:00,RS,386.0,"353,2",ESTRELA,Não,...,Feminino,0.0,0.0,1.0,0.0,"-29,50160055","-51,94784403",SPRF-RS,DEL04-RS,UOP02-DEL04-RS
10,496512,1082879.0,2023-01-01,domingo,00:55:00,RS,386.0,"353,2",ESTRELA,Não,...,Feminino,0.0,0.0,1.0,0.0,"-29,50160055","-51,94784403",SPRF-RS,DEL04-RS,UOP02-DEL04-RS
11,496512,1082877.0,2023-01-01,domingo,00:55:00,RS,386.0,"353,2",ESTRELA,Não,...,Feminino,0.0,0.0,1.0,0.0,"-29,50160055","-51,94784403",SPRF-RS,DEL04-RS,UOP02-DEL04-RS
12,496512,1082884.0,2023-01-01,domingo,00:55:00,RS,386.0,"353,2",ESTRELA,Não,...,Masculino,0.0,0.0,1.0,0.0,"-29,50160055","-51,94784403",SPRF-RS,DEL04-RS,UOP02-DEL04-RS
13,496512,1082224.0,2023-01-01,domingo,00:55:00,RS,386.0,"353,2",ESTRELA,Não,...,Masculino,0.0,0.0,1.0,0.0,"-29,50160055","-51,94784403",SPRF-RS,DEL04-RS,UOP02-DEL04-RS
14,496512,1082880.0,2023-01-01,domingo,00:55:00,RS,386.0,"353,2",ESTRELA,Não,...,Feminino,0.0,0.0,1.0,0.0,"-29,50160055","-51,94784403",SPRF-RS,DEL04-RS,UOP02-DEL04-RS
15,496512,1082879.0,2023-01-01,domingo,00:55:00,RS,386.0,"353,2",ESTRELA,Sim,...,Feminino,0.0,0.0,1.0,0.0,"-29,50160055","-51,94784403",SPRF-RS,DEL04-RS,UOP02-DEL04-RS
16,496512,1082877.0,2023-01-01,domingo,00:55:00,RS,386.0,"353,2",ESTRELA,Sim,...,Feminino,0.0,0.0,1.0,0.0,"-29,50160055","-51,94784403",SPRF-RS,DEL04-RS,UOP02-DEL04-RS
17,496512,1082884.0,2023-01-01,domingo,00:55:00,RS,386.0,"353,2",ESTRELA,Sim,...,Masculino,0.0,0.0,1.0,0.0,"-29,50160055","-51,94784403",SPRF-RS,DEL04-RS,UOP02-DEL04-RS
18,496512,1082224.0,2023-01-01,domingo,00:55:00,RS,386.0,"353,2",ESTRELA,Sim,...,Masculino,0.0,0.0,1.0,0.0,"-29,50160055","-51,94784403",SPRF-RS,DEL04-RS,UOP02-DEL04-RS
19,496512,1082880.0,2023-01-01,domingo,00:55:00,RS,386.0,"353,2",ESTRELA,Sim,...,Feminino,0.0,0.0,1.0,0.0,"-29,50160055","-51,94784403",SPRF-RS,DEL04-RS,UOP02-DEL04-RS

In [5]:
#visualizando as colunas do dataframes 2024
df_2024.columns

Index(['id', 'pesid', 'data_inversa', 'dia_semana', 'horario', 'uf', 'br',
       'km', 'municipio', 'causa_principal', 'causa_acidente',
       'ordem_tipo_acidente', 'tipo_acidente', 'classificacao_acidente',
       'fase_dia', 'sentido_via', 'condicao_metereologica', 'tipo_pista',
       'tracado_via', 'uso_solo', 'id_veiculo', 'tipo_veiculo', 'marca',
       'ano_fabricacao_veiculo', 'tipo_envolvido', 'estado_fisico', 'idade',
       'sexo', 'ilesos', 'feridos_leves', 'feridos_graves', 'mortos',
       'latitude', 'longitude', 'regional', 'delegacia', 'uop'],
      dtype='str')

In [6]:
df_2024.head(20)

,id,pesid,data_inversa,dia_semana,horario,uf,br,km,municipio,causa_principal,...,sexo,ilesos,feridos_leves,feridos_graves,mortos,latitude,longitude,regional,delegacia,uop
0,571772.0,1268971.0,2024-01-01,segunda-feira,00:05:00,RJ,101.0,"272,5",TANGUA,Sim,...,Masculino,0.0,0.0,0.0,1.0,-22.729360,-42.701125,SPRF-RJ,DEL02-RJ,UOP03-DEL02-RJ
1,571774.0,1268985.0,2024-01-01,segunda-feira,00:05:00,GO,153.0,"424,6",ANAPOLIS,Não,...,Feminino,1.0,0.0,0.0,0.0,-16.229185,-49.009797,SPRF-GO,DEL02-GO,UOP01-DEL02-GO
2,571774.0,1268985.0,2024-01-01,segunda-feira,00:05:00,GO,153.0,"424,6",ANAPOLIS,Sim,...,Feminino,1.0,0.0,0.0,0.0,-16.229185,-49.009797,SPRF-GO,DEL02-GO,UOP01-DEL02-GO
3,571777.0,1269020.0,2024-01-01,segunda-feira,01:45:00,ES,101.0,"264,1",SERRA,Sim,...,Masculino,1.0,0.0,0.0,0.0,-20.172928,-40.267364,SPRF-ES,DEL02-ES,UOP01-DEL02-ES
4,571778.0,1269028.0,2024-01-01,segunda-feira,00:45:00,SC,101.0,110,PENHA,Não,...,Masculino,1.0,0.0,0.0,0.0,-26.834770,-48.706151,SPRF-SC,DEL03-SC,UOP02-DEL03-SC
5,571778.0,1269045.0,2024-01-01,segunda-feira,00:45:00,SC,101.0,110,PENHA,Não,...,Feminino,0.0,1.0,0.0,0.0,-26.834770,-48.706151,SPRF-SC,DEL03-SC,UOP02-DEL03-SC
6,571778.0,1269028.0,2024-01-01,segunda-feira,00:45:00,SC,101.0,110,PENHA,Sim,...,Masculino,1.0,0.0,0.0,0.0,-26.834770,-48.706151,SPRF-SC,DEL03-SC,UOP02-DEL03-SC
7,571778.0,1269045.0,2024-01-01,segunda-feira,00:45:00,SC,101.0,110,PENHA,Sim,...,Feminino,0.0,1.0,0.0,0.0,-26.834770,-48.706151,SPRF-SC,DEL03-SC,UOP02-DEL03-SC
8,571779.0,1268998.0,2024-01-01,segunda-feira,01:45:00,RS,116.0,236,NOVO HAMBURGO,Sim,...,Feminino,1.0,0.0,0.0,0.0,-29.669385,-51.143047,SPRF-RS,DEL01-RS,UOP02-DEL01-RS
9,571779.0,1268999.0,2024-01-01,segunda-feira,01:45:00,RS,116.0,236,NOVO HAMBURGO,Sim,...,Masculino,1.0,0.0,0.0,0.0,-29.669385,-51.143047,SPRF-RS,DEL01-RS,UOP02-DEL01-RS
10,571779.0,1269000.0,2024-01-01,segunda-feira,01:45:00,RS,116.0,236,NOVO HAMBURGO,Sim,...,Feminino,1.0,0.0,0.0,0.0,-29.669385,-51.143047,SPRF-RS,DEL01-RS,UOP02-DEL01-RS
11,571779.0,1268976.0,2024-01-01,segunda-feira,01:45:00,RS,116.0,236,NOVO HAMBURGO,Sim,...,Masculino,1.0,0.0,0.0,0.0,-29.669385,-51.143047,SPRF-RS,DEL01-RS,UOP02-DEL01-RS
12,571780.0,1271043.0,2024-01-01,segunda-feira,01:50:00,PR,277.0,70,SAO JOSE DOS PINHAIS,Não,...,Feminino,0.0,1.0,0.0,0.0,-25.541123,-49.061834,SPRF-PR,DEL01-PR,UOP01-DEL01-PR
13,571780.0,1268977.0,2024-01-01,segunda-feira,01:50:00,PR,277.0,70,SAO JOSE DOS PINHAIS,Não,...,Masculino,0.0,1.0,0.0,0.0,-25.541123,-49.061834,SPRF-PR,DEL01-PR,UOP01-DEL01-PR
14,571780.0,1271043.0,2024-01-01,segunda-feira,01:50:00,PR,277.0,70,SAO JOSE DOS PINHAIS,Não,...,Feminino,0.0,1.0,0.0,0.0,-25.541123,-49.061834,SPRF-PR,DEL01-PR,UOP01-DEL01-PR
15,571780.0,1268977.0,2024-01-01,segunda-feira,01:50:00,PR,277.0,70,SAO JOSE DOS PINHAIS,Não,...,Masculino,0.0,1.0,0.0,0.0,-25.541123,-49.061834,SPRF-PR,DEL01-PR,UOP01-DEL01-PR
16,571780.0,1271043.0,2024-01-01,segunda-feira,01:50:00,PR,277.0,70,SAO JOSE DOS PINHAIS,Sim,...,Feminino,0.0,1.0,0.0,0.0,-25.541123,-49.061834,SPRF-PR,DEL01-PR,UOP01-DEL01-PR
17,571780.0,1268977.0,2024-01-01,segunda-feira,01:50:00,PR,277.0,70,SAO JOSE DOS PINHAIS,Sim,...,Masculino,0.0,1.0,0.0,0.0,-25.541123,-49.061834,SPRF-PR,DEL01-PR,UOP01-DEL01-PR
18,571780.0,1271043.0,2024-01-01,segunda-feira,01:50:00,PR,277.0,70,SAO JOSE DOS PINHAIS,Não,...,Feminino,0.0,1.0,0.0,0.0,-25.541123,-49.061834,SPRF-PR,DEL01-PR,UOP01-DEL01-PR
19,571780.0,1268977.0,2024-01-01,segunda-feira,01:50:00,PR,277.0,70,SAO JOSE DOS PINHAIS,Não,...,Masculino,0.0,1.0,0.0,0.0,-25.541123,-49.061834,SPRF-PR,DEL01-PR,UOP01-DEL01-PR

In [7]:
#visualizando as colunas do dataframes 2025
df_2025.columns

Index(['id', 'pesid', 'data_inversa', 'dia_semana', 'horario', 'uf', 'br',
       'km', 'municipio', 'causa_principal', 'causa_acidente',
       'ordem_tipo_acidente', 'tipo_acidente', 'classificacao_acidente',
       'fase_dia', 'sentido_via', 'condicao_metereologica', 'tipo_pista',
       'tracado_via', 'uso_solo', 'id_veiculo', 'tipo_veiculo', 'marca',
       'ano_fabricacao_veiculo', 'tipo_envolvido', 'estado_fisico', 'idade',
       'sexo', 'ilesos', 'feridos_leves', 'feridos_graves', 'mortos',
       'latitude', 'longitude', 'regional', 'delegacia', 'uop'],
      dtype='str')

In [8]:
df_2025.head(20)

,id,pesid,data_inversa,dia_semana,horario,uf,br,km,municipio,causa_principal,...,sexo,ilesos,feridos_leves,feridos_graves,mortos,latitude,longitude,regional,delegacia,uop
0,652468,1467636.0,2025-01-01,quarta-feira,00:30:00,PE,101.0,"89,5",JABOATAO DOS GUARARAPES,Sim,...,Não Informado,0.0,0.0,0.0,0.0,"-8,20760697","-34,98372005",SPRF-PE,DEL01-PE,UOP01-DEL01-PE
1,652468,1467635.0,2025-01-01,quarta-feira,00:30:00,PE,101.0,"89,5",JABOATAO DOS GUARARAPES,Sim,...,Feminino,0.0,1.0,0.0,0.0,"-8,20760697","-34,98372005",SPRF-PE,DEL01-PE,UOP01-DEL01-PE
2,652468,1467634.0,2025-01-01,quarta-feira,00:30:00,PE,101.0,"89,5",JABOATAO DOS GUARARAPES,Sim,...,Masculino,0.0,1.0,0.0,0.0,"-8,20760697","-34,98372005",SPRF-PE,DEL01-PE,UOP01-DEL01-PE
3,652468,1467637.0,2025-01-01,quarta-feira,00:30:00,PE,101.0,"89,5",JABOATAO DOS GUARARAPES,Sim,...,Não Informado,0.0,0.0,0.0,0.0,"-8,20760697","-34,98372005",SPRF-PE,DEL01-PE,UOP01-DEL01-PE
4,652469,1467628.0,2025-01-01,quarta-feira,00:50:00,SC,101.0,120,ITAJAI,Sim,...,Feminino,0.0,1.0,0.0,0.0,"-26,912758","-48,711998",SPRF-SC,DEL04-SC,UOP04-DEL04-SC
5,652469,1467627.0,2025-01-01,quarta-feira,00:50:00,SC,101.0,120,ITAJAI,Sim,...,Masculino,1.0,0.0,0.0,0.0,"-26,912758","-48,711998",SPRF-SC,DEL04-SC,UOP04-DEL04-SC
6,652470,1467671.0,2025-01-01,quarta-feira,01:15:00,GO,153.0,414,ANAPOLIS,Sim,...,Feminino,0.0,0.0,1.0,0.0,"-16,133518","-49,047565",SPRF-GO,DEL02-GO,UOP02-DEL02-GO
7,652470,1467672.0,2025-01-01,quarta-feira,01:15:00,GO,153.0,414,ANAPOLIS,Sim,...,Feminino,1.0,0.0,0.0,0.0,"-16,133518","-49,047565",SPRF-GO,DEL02-GO,UOP02-DEL02-GO
8,652470,1467670.0,2025-01-01,quarta-feira,01:15:00,GO,153.0,414,ANAPOLIS,Sim,...,Masculino,1.0,0.0,0.0,0.0,"-16,133518","-49,047565",SPRF-GO,DEL02-GO,UOP02-DEL02-GO
9,652470,1467669.0,2025-01-01,quarta-feira,01:15:00,GO,153.0,414,ANAPOLIS,Sim,...,Feminino,1.0,0.0,0.0,0.0,"-16,133518","-49,047565",SPRF-GO,DEL02-GO,UOP02-DEL02-GO
10,652470,1467668.0,2025-01-01,quarta-feira,01:15:00,GO,153.0,414,ANAPOLIS,Sim,...,Masculino,1.0,0.0,0.0,0.0,"-16,133518","-49,047565",SPRF-GO,DEL02-GO,UOP02-DEL02-GO
11,652471,1467729.0,2025-01-01,quarta-feira,02:00:00,PR,116.0,"11,3",COLOMBO,Sim,...,Masculino,1.0,0.0,0.0,0.0,"-25,37228723","-49,13813353",SPRF-PR,DEL01-PR,UOP02-DEL01-PR
12,652473,1467644.0,2025-01-01,quarta-feira,01:40:00,DF,20.0,"8,8",BRASILIA,Sim,...,Masculino,1.0,0.0,0.0,0.0,"-15,658386","-47,791534",SPRF-DF,DEL02-DF,UOP01-DEL02-DF
13,652473,1467643.0,2025-01-01,quarta-feira,01:40:00,DF,20.0,"8,8",BRASILIA,Sim,...,Feminino,1.0,0.0,0.0,0.0,"-15,658386","-47,791534",SPRF-DF,DEL02-DF,UOP01-DEL02-DF
14,652473,1467641.0,2025-01-01,quarta-feira,01:40:00,DF,20.0,"8,8",BRASILIA,Sim,...,Masculino,1.0,0.0,0.0,0.0,"-15,658386","-47,791534",SPRF-DF,DEL02-DF,UOP01-DEL02-DF
15,652474,1469333.0,2025-01-01,quarta-feira,02:30:00,PR,163.0,"219,7",CASCAVEL,Não,...,Feminino,0.0,1.0,0.0,0.0,"-24,897235","-53,533793",SPRF-PR,DEL04-PR,UOP01-DEL04-PR
16,652474,1467631.0,2025-01-01,quarta-feira,02:30:00,PR,163.0,"219,7",CASCAVEL,Não,...,Feminino,0.0,1.0,0.0,0.0,"-24,897235","-53,533793",SPRF-PR,DEL04-PR,UOP01-DEL04-PR
17,652474,1467630.0,2025-01-01,quarta-feira,02:30:00,PR,163.0,"219,7",CASCAVEL,Não,...,Masculino,1.0,0.0,0.0,0.0,"-24,897235","-53,533793",SPRF-PR,DEL04-PR,UOP01-DEL04-PR
18,652474,1469333.0,2025-01-01,quarta-feira,02:30:00,PR,163.0,"219,7",CASCAVEL,Não,...,Feminino,0.0,1.0,0.0,0.0,"-24,897235","-53,533793",SPRF-PR,DEL04-PR,UOP01-DEL04-PR
19,652474,1467631.0,2025-01-01,quarta-feira,02:30:00,PR,163.0,"219,7",CASCAVEL,Não,...,Feminino,0.0,1.0,0.0,0.0,"-24,897235","-53,533793",SPRF-PR,DEL04-PR,UOP01-DEL04-PR

In [9]:
#visualizando os tipos de dados das colunas do dataframe 2023
df_2023.dtypes

id                          int64
pesid                     float64
data_inversa                  str
dia_semana                    str
horario                       str
uf                            str
br                        float64
km                            str
municipio                     str
causa_principal               str
causa_acidente                str
ordem_tipo_acidente         int64
tipo_acidente                 str
classificacao_acidente        str
fase_dia                      str
sentido_via                   str
condicao_metereologica        str
tipo_pista                    str
tracado_via                   str
uso_solo                      str
id_veiculo                float64
tipo_veiculo                  str
marca                         str
ano_fabricacao_veiculo    float64
tipo_envolvido                str
estado_fisico                 str
idade                     float64
sexo                          str
ilesos                    float64
feridos_leves             float64
feridos_graves            float64
mortos                    float64
latitude                      str
longitude                     str
regional                      str
delegacia                     str
uop                           str
dtype: object

In [10]:
#latitude não apareceu nos tipos de dados - verificando se existe
"latitude" in df_2023.columns

True

In [11]:
df_2023["latitude"].dtype

In [12]:
#visualizando os tipos de dados das colunas do dataframe 2024
df_2024.dtypes

id                        float64
pesid                     float64
data_inversa                  str
dia_semana                    str
horario                       str
uf                            str
br                        float64
km                            str
municipio                     str
causa_principal               str
causa_acidente                str
ordem_tipo_acidente         int64
tipo_acidente                 str
classificacao_acidente        str
fase_dia                      str
sentido_via                   str
condicao_metereologica        str
tipo_pista                    str
tracado_via                   str
uso_solo                      str
id_veiculo                float64
tipo_veiculo                  str
marca                         str
ano_fabricacao_veiculo    float64
tipo_envolvido                str
estado_fisico                 str
idade                     float64
sexo                          str
ilesos                    float64
feridos_leves             float64
feridos_graves            float64
mortos                    float64
latitude                  float64
longitude                 float64
regional                      str
delegacia                     str
uop                           str
dtype: object

In [13]:
#Usando uma condição para verificar se a coluna latitude existe no dataframe 2024.

if "latitude" in df_2024.columns:
    print("A coluna 'latitude' existe.")
    print("Tipo de dado:", df_2024["latitude"].dtype)
else:
    print("A coluna 'latitude' NÃO existe.")

A coluna 'latitude' existe.
Tipo de dado: float64

In [14]:
#visualizando os tipos de dados das colunas do dataframe 2025
df_2025.dtypes

id                          int64
pesid                     float64
data_inversa                  str
dia_semana                    str
horario                       str
uf                            str
br                        float64
km                            str
municipio                     str
causa_principal               str
causa_acidente                str
ordem_tipo_acidente         int64
tipo_acidente                 str
classificacao_acidente        str
fase_dia                      str
sentido_via                   str
condicao_metereologica        str
tipo_pista                    str
tracado_via                   str
uso_solo                      str
id_veiculo                float64
tipo_veiculo                  str
marca                         str
ano_fabricacao_veiculo    float64
tipo_envolvido                str
estado_fisico                 str
idade                     float64
sexo                          str
ilesos                    float64
feridos_leves             float64
feridos_graves            float64
mortos                    float64
latitude                      str
longitude                     str
regional                      str
delegacia                     str
uop                           str
dtype: object

In [15]:
#Passando uma condição para verificar se a coluna latitude existe no dataframe 2025.

if "latitude" in df_2025.columns:
    print("A coluna 'latitude' existe.")
    print("Tipo de dado:", df_2025["latitude"].dtype)
else:
    print("A coluna 'latitude' NÃO existe.")

A coluna 'latitude' existe.
Tipo de dado: str

#ANALISANDO O TIPO DE DADOS, JÁ CONSEGUIR EXERGA TIPOS QUE PRECISAM SER CONVERTIDOS PARA OUTROS TIPOS MAIS ADEQUADOS.

data_inversa str para data /
horario str para hora /
longitude str para float (verificar porque está como str, pode ter valores nulos) /
latitude 2023 é str mudar para float (verificar porque está como str, pode ter valores nulos) /
latitude 2024 é float ( está ok) / 
latitude 2025 é str mudar para float e corrigir nulos /
pesid float para int /
id_veiculo float para int /
km float para int /
ano_fabricação float para int

In [16]:
#meu arquivo é muito grande difícil para visualizar os dados, então vou visualizar apenas as colunas com nulos

df_2023.isnull().sum()[df_2023.isnull().sum() > 0]

pesid                      55887
br                          1836
km                          1836
classificacao_acidente         3
id_veiculo                 20772
tipo_veiculo               20772
ano_fabricacao_veiculo     20772
tipo_envolvido             55887
estado_fisico              55887
idade                     105448
sexo                       55887
ilesos                     55887
feridos_leves              55887
feridos_graves             55887
mortos                     55887
regional                     150
delegacia                    557
uop                          656
dtype: int64

In [17]:
df_2024.isnull().sum()[df_2024.isnull().sum() > 0]

pesid                      57641
br                          1348
km                          1348
classificacao_acidente         3
id_veiculo                 19572
tipo_veiculo               19572
ano_fabricacao_veiculo     19572
tipo_envolvido             57641
estado_fisico              57641
idade                     109408
sexo                       57641
ilesos                     57641
feridos_leves              57641
feridos_graves             57641
mortos                     57641
regional                      27
delegacia                    183
uop                         1663
dtype: int64

In [18]:
df_2025.isnull().sum()[df_2025.isnull().sum() > 0]

pesid                     52465
br                         1263
km                         1263
classificacao_acidente        7
id_veiculo                16918
tipo_veiculo              16918
ano_fabricacao_veiculo    16918
tipo_envolvido            52465
estado_fisico             52465
idade                     96411
sexo                      52465
ilesos                    52465
feridos_leves             52465
feridos_graves            52465
mortos                    52465
regional                     16
delegacia                   190
uop                         436
dtype: int64

In [19]:
#verificando se os três anos tem as mesmas colunas com nulos

nulos_2023 = set(df_2023.columns[df_2023.isnull().any()])
nulos_2024 = set(df_2024.columns[df_2024.isnull().any()])
nulos_2025 = set(df_2025.columns[df_2025.isnull().any()])

In [20]:
#verificando se os três anos tem as mesmas colunas com nulos

mesmas_colunas_nulas = (nulos_2023 == nulos_2024 == nulos_2025)

mesmas_colunas_nulas

True